### ISSUE TITLE
Controller crash with empty log message?

### ISSUE THREAD

**Issue by vschiavoni** [splay-project/splay#16]
There seems to be an issue if splayds send empty messages;

```
E, [2014-08-21 17:37:16 #30223] ERROR -- : NoMethodError: undefined method `size' for nil:NilClass
/home/splayd/splay/src/controller/lib/logd.rb:120:in `extract_timestamp_msg'
/home/splayd/splay/src/controller/lib/logd.rb:214:in `run'
/home/splayd/splay/src/controller/lib/logd.rb:201:in `loop'
/home/splayd/splay/src/controller/lib/logd.rb:201:in `run'
/home/splayd/splay/src/controller/lib/logd.rb:129:in `initialize'
/home/splayd/splay/src/controller/lib/logd.rb:129:in `new'
/home/splayd/splay/src/controller/lib/logd.rb:129:in `run'
/home/splayd/splay/src/controller/lib/logd.rb:74:in `main'
/home/splayd/splay/src/controller/lib/logd.rb:60:in `loop'
/home/splayd/splay/src/controller/lib/logd.rb:60:in `main'
/home/splayd/splay/src/controller/lib/logd.rb:35:in `run'
/home/splayd/splay/src/controller/lib/logd.rb:34:in `initialize'
/home/splayd/splay/src/controller/lib/logd.rb:34:in `new'
/home/splayd/splay/src/controller/lib/logd.rb:34:in `run'
controller_fork.rb:55
controller_fork.rb:53:in `fork'
controller_fork.rb:53
controller_fork.rb:52:in `each'
controller_fork.rb:52
```

**Comment by vschiavoni** [comment]
One way to prevent this is to add more defensive checks here:
https://github.com/splay-project/splay/blob/master/src/controller/lib/logd.rb#L177
