### ISSUE TITLE
DBI:DatabaseError crashes the controller

### ISSUE THREAD

**Issue by vschiavoni** [splay-project/splay#17]
This is the stack-trace. 
One possible root cause is no more disk space available on the hard-drive of the machine running the controller. 
 
```
F, [2014-09-05 09:51:08 #15051] FATAL -- : DBI::DatabaseError: MySQL server has gone away
/home/splayd/.rvm/gems/ruby-1.8.7-p374/gems/dbd-mysql-0.4.4/lib/dbd/Mysql.rb:106:in `error'
/home/splayd/.rvm/gems/ruby-1.8.7-p374/gems/dbd-mysql-0.4.4/lib/dbd/mysql/statement.rb:42:in `execute'
/home/splayd/.rvm/gems/ruby-1.8.7-p374/gems/dbd-mysql-0.4.4/lib/dbd/mysql/database.rb:233:in `do'
/home/splayd/.rvm/gems/ruby-1.8.7-p374/gems/dbi-0.4.5/lib/dbi/handles/database.rb:106:in `do'
/home/splayd/splay/src/controller/lib/log_object.rb:34:in `send'
/home/splayd/splay/src/controller/lib/log_object.rb:34:in `method_missing'
/home/splayd/splay/src/controller/lib/splayd.rb:788:in `unavailable'
/home/splayd/splay/src/controller/lib/splayd.rb:366:in `main'
/home/splayd/splay/src/controller/lib/splayd.rb:126:in `run'
/home/splayd/splay/src/controller/lib/splayd.rb:123:in `initialize'
/home/splayd/splay/src/controller/lib/splayd.rb:123:in `new'
/home/splayd/splay/src/controller/lib/splayd.rb:123:in `run'
/home/splayd/splay/src/controller/lib/splayd.rb:82:in `main'
/home/splayd/splay/src/controller/lib/splayd.rb:76:in `loop'
/home/splayd/splay/src/controller/lib/splayd.rb:76:in `main'
/home/splayd/splay/src/controller/lib/splayd.rb:39:in `run'
/home/splayd/splay/src/controller/lib/splayd.rb:38:in `initialize'
/home/splayd/splay/src/controller/lib/splayd.rb:38:in `new'
/home/splayd/splay/src/controller/lib/splayd.rb:38:in `run'
controller_fork.rb:63
controller_fork.rb:60:in `fork'
controller_fork.rb:60
controller_fork.rb:59:in `each'
controller_fork.rb:59
```

**Comment by vschiavoni** [comment]
Possible fix:
```txt
To fix, you can increase the maximal packet size limit “max_allowed_packet” 
in my.cnf file, eg. set max_allowed_packet = 128M, 
then sudo /etc/init.d/mysql restart.
```

**Comment by vschiavoni** [comment]
Confirmed even in more recent versions of MySQL (5.6).
