### ISSUE TITLE
splay-cli server error

### ISSUE THREAD

**Issue by vschiavoni** [splay-project/splay#22]
Could not retrieve the command that generated this stack trace: 
```ruby
[2014-09-29 22:44:46] ERROR JSON::GeneratorError: only generation of JSON objects or arrays allowed
        /home/splayd/.rvm/gems/ruby-1.8.7-p374/gems/json-1.8.1/lib/json/common.rb:223:in `generate'
        /home/splayd/.rvm/gems/ruby-1.8.7-p374/gems/json-1.8.1/lib/json/common.rb:223:in `unparse'
        cli-server.rb:47:in `do_POST'
        /home/splayd/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/webrick/httpservlet/abstract.rb:35:in `__send__'
        /home/splayd/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/webrick/httpservlet/abstract.rb:35:in `service'
        /home/splayd/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
        /home/splayd/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
        /home/splayd/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
        /home/splayd/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/webrick/server.rb:162:in `start'
        /home/splayd/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
        /home/splayd/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/webrick/server.rb:95:in `start'
        /home/splayd/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/webrick/server.rb:92:in `each'
        /home/splayd/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/webrick/server.rb:92:in `start'
        /home/splayd/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/webrick/server.rb:23:in `start'
        /home/splayd/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/webrick/server.rb:82:in `start'
        cli-server.rb:54
```

**Comment by vschiavoni** [comment]
Cannot reproduce.
