### ISSUE TITLE
Controller crash 

### ISSUE THREAD

**Issue by vschiavoni** [splay-project/splay#23]
Controller under Ruby 1.8.7, splay deamons running Lua 5.2. 

```ruby
I, [2015-01-13 17:31:08 #19067]  INFO -- : Splayd (1) remote-time before job: 17:31:07.801396 DIFF: 0.7472 RTT: 0.0007865
E, [2015-01-13 17:31:08 #19067] ERROR -- : TypeError: no implicit conversion to float from nil
/home/ubuntu/splay/src/controller/lib/logd.rb:235:in `-'
/home/ubuntu/splay/src/controller/lib/logd.rb:235:in `run'
/home/ubuntu/splay/src/controller/lib/logd.rb:129:in `initialize'
/home/ubuntu/splay/src/controller/lib/logd.rb:129:in `new'
/home/ubuntu/splay/src/controller/lib/logd.rb:129:in `run'
/home/ubuntu/splay/src/controller/lib/logd.rb:74:in `main'
/home/ubuntu/splay/src/controller/lib/logd.rb:60:in `loop'
/home/ubuntu/splay/src/controller/lib/logd.rb:60:in `main'
/home/ubuntu/splay/src/controller/lib/logd.rb:35:in `run'
/home/ubuntu/splay/src/controller/lib/logd.rb:34:in `initialize'
/home/ubuntu/splay/src/controller/lib/logd.rb:34:in `new'
/home/ubuntu/splay/src/controller/lib/logd.rb:34:in `run'
controller_fork.rb:55
controller_fork.rb:53:in `fork'
controller_fork.rb:53
controller_fork.rb:52:in `each'
controller_fork.rb:52
```

**Comment by vschiavoni** [comment]
Fixed by cf1266c6c0203bff7b3ac90544b90a7ff1efec90
